// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vbchlbrdwtqfccdydwzw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZiY2hsYnJkd3RxZmNjZHlkd3p3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDE5MDUzMTAsImV4cCI6MjA1NzQ4MTMxMH0.jrqXAcX10_WmVRf1WS8BO1arGuNmPAEJ9rL_F81qI6A";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);